server:
  port: 8080
spring:
  application:
    name: "crediya-reporting"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
